// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdCaBJvCkEHsp_Q0gbiBQ6oFgufuALgVk',
    appId: '1:105703998110:web:b00358afdd6a6b8d41b18f',
    messagingSenderId: '105703998110',
    projectId: 'projectppb-b5afc',
    authDomain: 'projectppb-b5afc.firebaseapp.com',
    storageBucket: 'projectppb-b5afc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA89SteVBCt8KbxwZiSxl62wq4JMHMJEPk',
    appId: '1:105703998110:android:71870b69d94d388d41b18f',
    messagingSenderId: '105703998110',
    projectId: 'projectppb-b5afc',
    storageBucket: 'projectppb-b5afc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh2yF61Lnu3ZQt0u8PcpTQ7mY4VFg3Vjc',
    appId: '1:105703998110:ios:75cd1859dcfb6b2041b18f',
    messagingSenderId: '105703998110',
    projectId: 'projectppb-b5afc',
    storageBucket: 'projectppb-b5afc.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh2yF61Lnu3ZQt0u8PcpTQ7mY4VFg3Vjc',
    appId: '1:105703998110:ios:75cd1859dcfb6b2041b18f',
    messagingSenderId: '105703998110',
    projectId: 'projectppb-b5afc',
    storageBucket: 'projectppb-b5afc.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdCaBJvCkEHsp_Q0gbiBQ6oFgufuALgVk',
    appId: '1:105703998110:web:8bfaf12f2cd367ae41b18f',
    messagingSenderId: '105703998110',
    projectId: 'projectppb-b5afc',
    authDomain: 'projectppb-b5afc.firebaseapp.com',
    storageBucket: 'projectppb-b5afc.appspot.com',
  );

}